<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Aruba', 'iso_code' => 'ABW'],
            ['name' => 'Afghanistan', 'iso_code' => 'AFG'],
            ['name' => 'Angola', 'iso_code' => 'AGO'],
            ['name' => 'Anguilla', 'iso_code' => 'AIA'],
            ['name' => 'Åland Islands', 'iso_code' => 'ALA'],
            ['name' => 'Albania', 'iso_code' => 'ALB'],
            ['name' => 'Andorra', 'iso_code' => 'AND'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'ARE'],
            ['name' => 'Argentina', 'iso_code' => 'ARG'],
            ['name' => 'Armenia', 'iso_code' => 'ARM'],
            ['name' => 'American Samoa', 'iso_code' => 'ASM'],
            ['name' => 'Antarctica', 'iso_code' => 'ATA'],
            ['name' => 'French Southern Territories', 'iso_code' => 'ATF'],
            ['name' => 'Antigua and Barbuda', 'iso_code' => 'ATG'],
            ['name' => 'Australia', 'iso_code' => 'AUS'],
            ['name' => 'Austria', 'iso_code' => 'AUT'],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZE'],
            ['name' => 'Burundi', 'iso_code' => 'BDI'],
            ['name' => 'Belgium', 'iso_code' => 'BEL'],
            ['name' => 'Benin', 'iso_code' => 'BEN'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'iso_code' => 'BES'],
            ['name' => 'Burkina Faso', 'iso_code' => 'BFA'],
            ['name' => 'Bangladesh', 'iso_code' => 'BGD'],
            ['name' => 'Bulgaria', 'iso_code' => 'BGR'],
            ['name' => 'Bahrain', 'iso_code' => 'BHR'],
            ['name' => 'Bahamas', 'iso_code' => 'BHS'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BIH'],
            ['name' => 'Saint Barthélemy', 'iso_code' => 'BLM'],
            ['name' => 'Belarus', 'iso_code' => 'BLR'],
            ['name' => 'Belize', 'iso_code' => 'BLZ'],
            ['name' => 'Bermuda', 'iso_code' => 'BMU'],
            ['name' => 'Bolivia (Plurinational State of)', 'iso_code' => 'BOL'],
            ['name' => 'Brazil', 'iso_code' => 'BRA'],
            ['name' => 'Barbados', 'iso_code' => 'BRB'],
            ['name' => 'Brunei Darussalam', 'iso_code' => 'BRN'],
            ['name' => 'Bhutan', 'iso_code' => 'BTN'],
            ['name' => 'Bouvet Island', 'iso_code' => 'BVT'],
            ['name' => 'Botswana', 'iso_code' => 'BWA'],
            ['name' => 'Central African Republic', 'iso_code' => 'CAF'],
            ['name' => 'Canada', 'iso_code' => 'CAN'],
            ['name' => 'Cocos (Keeling) Islands', 'iso_code' => 'CCK'],
            ['name' => 'Switzerland', 'iso_code' => 'CHE'],
            ['name' => 'Chile', 'iso_code' => 'CHL'],
            ['name' => 'China', 'iso_code' => 'CHN'],
            ['name' => 'Côte d\'Ivoire', 'iso_code' => 'CIV'],
            ['name' => 'Cameroon', 'iso_code' => 'CMR'],
            ['name' => 'Congo, Democratic Republic of the', 'iso_code' => 'COD'],
            ['name' => 'Congo', 'iso_code' => 'COG'],
            ['name' => 'Cook Islands', 'iso_code' => 'COK'],
            ['name' => 'Colombia', 'iso_code' => 'COL'],
            ['name' => 'Comoros', 'iso_code' => 'COM'],
            ['name' => 'Cape Verde', 'iso_code' => 'CPV'],
            ['name' => 'Costa Rica', 'iso_code' => 'CRI'],
            ['name' => 'Cuba', 'iso_code' => 'CUB'],
            ['name' => 'Curaçao', 'iso_code' => 'CUW'],
            ['name' => 'Christmas Island', 'iso_code' => 'CXR'],
            ['name' => 'Cyprus', 'iso_code' => 'CYP'],
            ['name' => 'Czech Republic', 'iso_code' => 'CZE'],
            ['name' => 'Germany', 'iso_code' => 'DEU'],
            ['name' => 'Djibouti', 'iso_code' => 'DJI'],
            ['name' => 'Denmark', 'iso_code' => 'DNK'],
            ['name' => 'Dominica', 'iso_code' => 'DMA'],
            ['name' => 'Dominican Republic', 'iso_code' => 'DOM'],
            ['name' => 'Algeria', 'iso_code' => 'DZA'],
            ['name' => 'Ecuador', 'iso_code' => 'ECU'],
            ['name' => 'Estonia', 'iso_code' => 'EST'],
            ['name' => 'Egypt', 'iso_code' => 'EGY'],
            ['name' => 'Western Sahara', 'iso_code' => 'ESH'],
            ['name' => 'Eritrea', 'iso_code' => 'ERI'],
            ['name' => 'Spain', 'iso_code' => 'ESP'],
            ['name' => 'Ethiopia', 'iso_code' => 'ETH'],
            ['name' => 'Finland', 'iso_code' => 'FIN'],
            ['name' => 'Fiji', 'iso_code' => 'FJI'],
            ['name' => 'France', 'iso_code' => 'FRA'],
            ['name' => 'Gabon', 'iso_code' => 'GAB'],
            ['name' => 'United Kingdom', 'iso_code' => 'GBR'],
            ['name' => 'Grenada', 'iso_code' => 'GRD'],
            ['name' => 'Georgia', 'iso_code' => 'GEO'],
            ['name' => 'Ghana', 'iso_code' => 'GHA'],
            ['name' => 'Gambia', 'iso_code' => 'GMB'],
            ['name' => 'Guinea', 'iso_code' => 'GIN'],
            ['name' => 'Guadeloupe', 'iso_code' => 'GLP'],
            ['name' => 'Equatorial Guinea', 'iso_code' => 'GNQ'],
            ['name' => 'Greece', 'iso_code' => 'GRC'],
            ['name' => 'Greenland', 'iso_code' => 'GRL'],
            ['name' => 'Guatemala', 'iso_code' => 'GTM'],
            ['name' => 'Guam', 'iso_code' => 'GUM'],
            ['name' => 'Guinea-Bissau', 'iso_code' => 'GNB'],
            ['name' => 'Guyana', 'iso_code' => 'GUY'],
            ['name' => 'Hong Kong', 'iso_code' => 'HKG'],
            ['name' => 'Honduras', 'iso_code' => 'HND'],
            ['name' => 'Croatia', 'iso_code' => 'HRV'],
            ['name' => 'Haiti', 'iso_code' => 'HTI'],
            ['name' => 'Hungary', 'iso_code' => 'HUN'],
            ['name' => 'Indonesia', 'iso_code' => 'IDN'],
            ['name' => 'Ireland', 'iso_code' => 'IRL'],
            ['name' => 'Israel', 'iso_code' => 'ISR'],
            ['name' => 'India', 'iso_code' => 'IND'],
            ['name' => 'Iraq', 'iso_code' => 'IRQ'],
            ['name' => 'Iran', 'iso_code' => 'IRN'],
            ['name' => 'Iceland', 'iso_code' => 'ISL'],
            ['name' => 'Italy', 'iso_code' => 'ITA'],
            ['name' => 'Jamaica', 'iso_code' => 'JAM'],
            ['name' => 'Jordan', 'iso_code' => 'JOR'],
            ['name' => 'Japan', 'iso_code' => 'JPN'],
            ['name' => 'Kenya', 'iso_code' => 'KEN'],
            ['name' => 'South Korea', 'iso_code' => 'KOR'],
            ['name' => 'Kuwait', 'iso_code' => 'KWT'],
            ['name' => 'Kazakhstan', 'iso_code' => 'KAZ'],
            ['name' => 'Laos', 'iso_code' => 'LAO'],
            ['name' => 'Lebanon', 'iso_code' => 'LBN'],
            ['name' => 'Liberia', 'iso_code' => 'LBR'],
            ['name' => 'Libya', 'iso_code' => 'LBY'],
            ['name' => 'Saint Lucia', 'iso_code' => 'LCA'],
            ['name' => 'Sri Lanka', 'iso_code' => 'LKA'],
            ['name' => 'Lesotho', 'iso_code' => 'LSO'],
            ['name' => 'Lithuania', 'iso_code' => 'LTU'],
            ['name' => 'Luxembourg', 'iso_code' => 'LUX'],
            ['name' => 'Latvia', 'iso_code' => 'LVA'],
            ['name' => 'Morocco', 'iso_code' => 'MAR'],
            ['name' => 'Monaco', 'iso_code' => 'MCO'],
            ['name' => 'Moldova', 'iso_code' => 'MDA'],
            ['name' => 'Madagascar', 'iso_code' => 'MDG'],
            ['name' => 'Maldives', 'iso_code' => 'MDV'],
            ['name' => 'Mexico', 'iso_code' => 'MEX'],
            ['name' => 'Malaysia', 'iso_code' => 'MYS'],
            ['name' => 'Mozambique', 'iso_code' => 'MOZ'],
            ['name' => 'Namibia', 'iso_code' => 'NAM'],
            ['name' => 'Nigeria', 'iso_code' => 'NGA'],
            ['name' => 'Norway', 'iso_code' => 'NOR'],
            ['name' => 'Nepal', 'iso_code' => 'NPL'],
            ['name' => 'Netherlands', 'iso_code' => 'NLD'],
            ['name' => 'New Zealand', 'iso_code' => 'NZL'],
            ['name' => 'Oman', 'iso_code' => 'OMN'],
            ['name' => 'Pakistan', 'iso_code' => 'PAK'],
            ['name' => 'Panama', 'iso_code' => 'PAN'],
            ['name' => 'Philippines', 'iso_code' => 'PHL'],
            ['name' => 'Poland', 'iso_code' => 'POL'],
            ['name' => 'Portugal', 'iso_code' => 'PRT'],
            ['name' => 'Qatar', 'iso_code' => 'QAT'],
            ['name' => 'Romania', 'iso_code' => 'ROU'],
            ['name' => 'Russia', 'iso_code' => 'RUS'],
            ['name' => 'Rwanda', 'iso_code' => 'RWA'],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SAU'],
            ['name' => 'Senegal', 'iso_code' => 'SEN'],
            ['name' => 'Serbia', 'iso_code' => 'SRB'],
            ['name' => 'Seychelles', 'iso_code' => 'SYC'],
            ['name' => 'Singapore', 'iso_code' => 'SGP'],
            ['name' => 'Slovakia', 'iso_code' => 'SVK'],
            ['name' => 'Slovenia', 'iso_code' => 'SVN'],
            ['name' => 'Somalia', 'iso_code' => 'SOM'],
            ['name' => 'South Africa', 'iso_code' => 'ZAF'],
            ['name' => 'South Sudan', 'iso_code' => 'SSD'],
            ['name' => 'Sudan', 'iso_code' => 'SDN'],
            ['name' => 'Suriname', 'iso_code' => 'SUR'],
            ['name' => 'Svalbard and Jan Mayen', 'iso_code' => 'SJM'],
            ['name' => 'Swaziland', 'iso_code' => 'SWZ'],
            ['name' => 'Sweden', 'iso_code' => 'SWE'],
            ['name' => 'Syria', 'iso_code' => 'SYR'],
            ['name' => 'Tajikistan', 'iso_code' => 'TJK'],
            ['name' => 'Thailand', 'iso_code' => 'THA'],
            ['name' => 'Timor-Leste', 'iso_code' => 'TLS'],
            ['name' => 'Togo', 'iso_code' => 'TGO'],
            ['name' => 'Tokelau', 'iso_code' => 'TKL'],
            ['name' => 'Tonga', 'iso_code' => 'TON'],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TTO'],
            ['name' => 'Tunisia', 'iso_code' => 'TUN'],
            ['name' => 'Turkey', 'iso_code' => 'TUR'],
            ['name' => 'Tuvalu', 'iso_code' => 'TUV'],
            ['name' => 'Taiwan, Province of China', 'iso_code' => 'TWN'],
            ['name' => 'Tanzania, United Republic of', 'iso_code' => 'TZA'],
            ['name' => 'Uganda', 'iso_code' => 'UGA'],
            ['name' => 'Ukraine', 'iso_code' => 'UKR'],
            ['name' => 'United States Minor Outlying Islands', 'iso_code' => 'UMI'],
            ['name' => 'Uruguay', 'iso_code' => 'URY'],
            ['name' => 'United States of America', 'iso_code' => 'USA'],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZB'],
            ['name' => 'Holy See (Vatican City State)', 'iso_code' => 'VAT'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VCT'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'iso_code' => 'VEN'],
            ['name' => 'Virgin Islands, British', 'iso_code' => 'VGB'],
            ['name' => 'Virgin Islands, U.S.', 'iso_code' => 'VIR'],
            ['name' => 'Viet Nam', 'iso_code' => 'VNM'],
            ['name' => 'Vanuatu', 'iso_code' => 'VUT'],
            ['name' => 'Wallis and Futuna', 'iso_code' => 'WLF'],
            ['name' => 'Samoa', 'iso_code' => 'WSM'],
            ['name' => 'Yemen', 'iso_code' => 'YEM'],
            ['name' => 'Zambia', 'iso_code' => 'ZMB'],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZWE'],
        ];

        DB::table('countries')->insert($countries);
    }
}
